//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var CardAttempts = newCardAttemptsTable("", "card_attempts", "")

type cardAttemptsTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnString
	CardID       sqlite.ColumnString
	QualityScore sqlite.ColumnInteger
	CreatedAt    sqlite.ColumnTimestamp
	UpdatedAt    sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CardAttemptsTable struct {
	cardAttemptsTable

	EXCLUDED cardAttemptsTable
}

// AS creates new CardAttemptsTable with assigned alias
func (a CardAttemptsTable) AS(alias string) *CardAttemptsTable {
	return newCardAttemptsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CardAttemptsTable with assigned schema name
func (a CardAttemptsTable) FromSchema(schemaName string) *CardAttemptsTable {
	return newCardAttemptsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CardAttemptsTable with assigned table prefix
func (a CardAttemptsTable) WithPrefix(prefix string) *CardAttemptsTable {
	return newCardAttemptsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CardAttemptsTable with assigned table suffix
func (a CardAttemptsTable) WithSuffix(suffix string) *CardAttemptsTable {
	return newCardAttemptsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCardAttemptsTable(schemaName, tableName, alias string) *CardAttemptsTable {
	return &CardAttemptsTable{
		cardAttemptsTable: newCardAttemptsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newCardAttemptsTableImpl("", "excluded", ""),
	}
}

func newCardAttemptsTableImpl(schemaName, tableName, alias string) cardAttemptsTable {
	var (
		IDColumn           = sqlite.StringColumn("id")
		CardIDColumn       = sqlite.StringColumn("card_id")
		QualityScoreColumn = sqlite.IntegerColumn("quality_score")
		CreatedAtColumn    = sqlite.TimestampColumn("created_at")
		UpdatedAtColumn    = sqlite.TimestampColumn("updated_at")
		allColumns         = sqlite.ColumnList{IDColumn, CardIDColumn, QualityScoreColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = sqlite.ColumnList{CardIDColumn, QualityScoreColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns     = sqlite.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return cardAttemptsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		CardID:       CardIDColumn,
		QualityScore: QualityScoreColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
