//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var CardTags = newCardTagsTable("", "card_tags", "")

type cardTagsTable struct {
	sqlite.Table

	// Columns
	CardID    sqlite.ColumnString
	TagID     sqlite.ColumnString
	CreatedAt sqlite.ColumnTimestamp
	UpdatedAt sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CardTagsTable struct {
	cardTagsTable

	EXCLUDED cardTagsTable
}

// AS creates new CardTagsTable with assigned alias
func (a CardTagsTable) AS(alias string) *CardTagsTable {
	return newCardTagsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CardTagsTable with assigned schema name
func (a CardTagsTable) FromSchema(schemaName string) *CardTagsTable {
	return newCardTagsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CardTagsTable with assigned table prefix
func (a CardTagsTable) WithPrefix(prefix string) *CardTagsTable {
	return newCardTagsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CardTagsTable with assigned table suffix
func (a CardTagsTable) WithSuffix(suffix string) *CardTagsTable {
	return newCardTagsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCardTagsTable(schemaName, tableName, alias string) *CardTagsTable {
	return &CardTagsTable{
		cardTagsTable: newCardTagsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newCardTagsTableImpl("", "excluded", ""),
	}
}

func newCardTagsTableImpl(schemaName, tableName, alias string) cardTagsTable {
	var (
		CardIDColumn    = sqlite.StringColumn("card_id")
		TagIDColumn     = sqlite.StringColumn("tag_id")
		CreatedAtColumn = sqlite.TimestampColumn("created_at")
		UpdatedAtColumn = sqlite.TimestampColumn("updated_at")
		allColumns      = sqlite.ColumnList{CardIDColumn, TagIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = sqlite.ColumnList{CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = sqlite.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return cardTagsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		CardID:    CardIDColumn,
		TagID:     TagIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
