//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Cards = newCardsTable("", "cards", "")

type cardsTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnString
	Question     sqlite.ColumnString
	Answer       sqlite.ColumnString
	Examples     sqlite.ColumnString
	Tradeoffs    sqlite.ColumnString
	CardType     sqlite.ColumnString
	CreatedAt    sqlite.ColumnTimestamp
	UpdatedAt    sqlite.ColumnTimestamp
	EaseFactor   sqlite.ColumnFloat
	IntervalDays sqlite.ColumnInteger
	DueDate      sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CardsTable struct {
	cardsTable

	EXCLUDED cardsTable
}

// AS creates new CardsTable with assigned alias
func (a CardsTable) AS(alias string) *CardsTable {
	return newCardsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CardsTable with assigned schema name
func (a CardsTable) FromSchema(schemaName string) *CardsTable {
	return newCardsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CardsTable with assigned table prefix
func (a CardsTable) WithPrefix(prefix string) *CardsTable {
	return newCardsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CardsTable with assigned table suffix
func (a CardsTable) WithSuffix(suffix string) *CardsTable {
	return newCardsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCardsTable(schemaName, tableName, alias string) *CardsTable {
	return &CardsTable{
		cardsTable: newCardsTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newCardsTableImpl("", "excluded", ""),
	}
}

func newCardsTableImpl(schemaName, tableName, alias string) cardsTable {
	var (
		IDColumn           = sqlite.StringColumn("id")
		QuestionColumn     = sqlite.StringColumn("question")
		AnswerColumn       = sqlite.StringColumn("answer")
		ExamplesColumn     = sqlite.StringColumn("examples")
		TradeoffsColumn    = sqlite.StringColumn("tradeoffs")
		CardTypeColumn     = sqlite.StringColumn("card_type")
		CreatedAtColumn    = sqlite.TimestampColumn("created_at")
		UpdatedAtColumn    = sqlite.TimestampColumn("updated_at")
		EaseFactorColumn   = sqlite.FloatColumn("ease_factor")
		IntervalDaysColumn = sqlite.IntegerColumn("interval_days")
		DueDateColumn      = sqlite.TimestampColumn("due_date")
		allColumns         = sqlite.ColumnList{IDColumn, QuestionColumn, AnswerColumn, ExamplesColumn, TradeoffsColumn, CardTypeColumn, CreatedAtColumn, UpdatedAtColumn, EaseFactorColumn, IntervalDaysColumn, DueDateColumn}
		mutableColumns     = sqlite.ColumnList{QuestionColumn, AnswerColumn, ExamplesColumn, TradeoffsColumn, CardTypeColumn, CreatedAtColumn, UpdatedAtColumn, EaseFactorColumn, IntervalDaysColumn, DueDateColumn}
		defaultColumns     = sqlite.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, EaseFactorColumn, IntervalDaysColumn}
	)

	return cardsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Question:     QuestionColumn,
		Answer:       AnswerColumn,
		Examples:     ExamplesColumn,
		Tradeoffs:    TradeoffsColumn,
		CardType:     CardTypeColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		EaseFactor:   EaseFactorColumn,
		IntervalDays: IntervalDaysColumn,
		DueDate:      DueDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
